import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./_global/footer/page";
import { Navbar } from "./_global/navigation/page";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Load Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Optional: Specify weights
  display: "swap", // Ensures fast rendering by swapping
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`} suppressHydrationWarning>
        <Navbar />
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
